### ISSUE TITLE
Evaluate possibility of service to service injection

### ISSUE THREAD

**Issue by philippkumar** [techatspree/roboject#2]

**Comment by ebiermann** [comment]
In general injection of services into other services is possible. One problem is the order of bindings. Assuming an activity, a roboect service A and a normal service B injected into A.
1. Activity calls bindService on A
2. onCreate() on Service A is called
3. Service A calls bindService on B in its onCreate()-Method
4. onBind() in service A is called and returns the Binder Object to the activity
5. onReady() is called on the activity because A is bound (but actually not working yey)
6. onBind() in service B is called and returns the Binder Object to service A
7. onReady() is called on service A which is now fully functional

Currently onReady() on the managed object is called by the ServiceInjector once all services are bound. This is not enough for roboject services which also are required to be ready. The idea would be to register callbacks with roboject services which are called in its onReady() method. The ServiceInjector needs to differentiate between normal services and roboject services. The former is ready as soon as it is bound, the second is ready as soon as the callback method is called. This might be trick but doable.

The main problem is how to register callbacks with the roboject services without having special requirements to the binder object (like a getService() method)?
